name: Download All Releases as Artifact

on:
  push:
    tags:
      - 'v*'

jobs:
  download-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all releases
        uses: robinraju/release-downloader@v1
        with:
          repository: 'owner/repo'
          all: true
          directory: './releases'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path:./releases
