name: Release Downloader

on:
  # Add a trigger event, such as "push" or "schedule"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: release-downloader
        uses: robinraju/release-downloader@v1.11
        with:
          repository: Pixelsuft/em-xash
          latest: true
          fileName: '*'
          #... other optional inputs...
